PXC-4369: PXC 8.0.36 refresh - Q1 2024 (Fix compilation errors on CentOS-7)
https://perconadev.atlassian.net/browse/PXC-4369

***
Fixed the compilation errors on CentOS-7.

1. OPENSSL_VERSION_MAJOR is not defined in openssl 1.1.1, replaced it
   with OPENSSL_VERSION_NUMBER.
2. Fixed the error due to -Werror=write-strings

=== error begin ===

/opt/percona-xtradb-cluster/percona-xtradb-cluster-galera/galerautils/tests/gu_asio_test.cpp:964:5: error: "OPENSSL_VERSION_MAJOR" is not defined, evaluates to 0 [-Werror=undef]
  964 | #if OPENSSL_VERSION_MAJOR < 3
      |     ^~~~~~~~~~~~~~~~~~~~~
/opt/percona-xtradb-cluster/percona-xtradb-cluster-galera/galerautils/tests/gu_asio_test.cpp: In function ‘void set_x509v3_extensions(X509*, X509*)’:
/opt/percona-xtradb-cluster/percona-xtradb-cluster-galera/galerautils/tests/gu_asio_test.cpp:1055:43: error: ISO C++ forbids converting a string constant to ‘char*’ [-Werror=write-strings]
 1055 |     if (!X509V3_EXT_add_nconf(conf, &ctx, "extensions", x509))
      |                                           ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors

=== error end ===