PXC-4369: PXC 8.0.36 refresh - Q1 2024 (merge release_26.4.17 compilation error fixed)
***
Fixed the compilation error due to variable length array in gu_log.c
when maintainer mode enabled.

galerautils/src/gu_log.c:141:5: error: ISO C90 forbids variable length array ‘string’ [-Werror=vla]
  141 |     char  string[max_string]; /** @note: this can cause stack overflow
      |     ^~~~
cc1: all warnings being treated as errors